keys:
  - &admin CE243917D8877F3AFE5814335850468557847C77
  - &desktop age1m83y7m8yx53fdqd2ttm63ncv7nu0reweafufuhfdyc0e927f44fsxx97f0
  - &yc-hk-1 age1h8wlkmqz9p4p5l9m69kzr2k8guqym7jt46j93egvum7fvmswy3tsu80agu

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *desktop
          - *yc-hk-1
  - path_regex: secrets/hosts/nixos-desktop\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *desktop
  - path_regex: secrets/hosts/yc-hk-1\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *yc-hk-1
