# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  # boot.kernelModules = [ "kvm-intel" "ntfs3" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cf59327d-2942-da48-870d-dd8a2b60e450";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4daf6a92-7e38-4198-a4ae-6c763dea81ef";
    fsType = "btrfs";
    neededForBoot = true;
    options= [
      "defaults"
      "compress=zstd"
      "noatime"
      "subvol=@home"
    ];
  };

  fileSystems."/Data1" = {
    device = "/dev/disk/by-uuid/6478644576DDF756";
    fsType = "ntfs3";
  };

  fileSystems."/Data" = {
    device = "/dev/disk/by-uuid/5B1E7D0DCF4C79EF";
    fsType = "ntfs3";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/DD5A-104A";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp10s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
