[General]
name=default-dark

[Control/look]
theme=default-light

[Color]
# 背景
BackgroundColor=#282a36
BackgroundOpacity=1.0

# 选区颜色
CandidateBackgroundColor=#44475a

# 提示颜色
HintColor=#6272a4

# 文字颜色
CandidateTextColor=#f8f8f2
PreeditTextColor=#f8f8f2

# 对齐方式
Alignment=0
CenterCJK打底色=false

# 字体
Font="Maple Mono NF CN 11"
MenuFont="Maple Mono NF CN 10"
TrayFont="Maple Mono NF CN 10"

# 显示设置
ShowPreedit=true
ShowTitle=false
ShowPreeditString=true
MaxCandidateCount=10
PageUpWithScrollWheel=true
PageDownWithScrollWheel=true

# 参数设置
EnableReadOnly=true
VKey3Center=false
HorizontalText=false

# 特殊设置
EnableContinuousHint=true
AutoProtect=true
AutoSelect=true
AutoSelectAfterZeroKeep=false
AutoCommit=false
AutoScroll=true
AutoSecondStageCommit=true
CancelSecondStageCommit=false
CenterCJKCandidate=true
Completion=5
CompletionWithSpace=false
CompletionAutoSelect=true
CompletionVisible=true
CommitTimestamp=0
DefineFont=false
ExtraAddSpace=true
ExtraFont=true
ExtraSpacing=0
FontEnableSpacing=true
FontWeight=400
FontSpacing=0
FontSimpChinese=false
FontWidthSpacing=0
FontWidthSpacingAuto=false
IgnoreUserInput=false
KeyContinousCommit=false
KeyPing=true
KeepPreedit=true
VerticalCandidateList=false
