{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  cfg = config.rhencloud.browser;
in
{
  options.rhencloud.browser.enable = mkEnableOption "browser and editor";

  config = mkIf cfg.enable {
    programs.chromium = {
      enable = false;
      package = pkgs.brave;
      extensions = [
        "bgnkhhnnamicmpeenaelnjfhikgbkllg"
        "ndcooeababalnlpkfedmmbbbgkljhpjf"
        "lildghglkgcoanblbmenbefhnhifghjj"
        "nngceckbapebfimnlniiiahkandclblb"
        "jlgkpaicikihijadgifklkbpdajbkhjo"
      ];
    };

    programs.vscode = {
      enable = true;
      profiles.default.userSettings = {
        "workbench.colorTheme" = "NoctaliaTheme";
      };
    };

    # noctalia 社区模板只会渲染主题 JSON，扩展清单由这里补齐，使 VS Code 能识别该主题。
    home.file.".vscode/extensions/noctalia.noctaliatheme-0.0.5/package.json".text = builtins.toJSON {
      name = "noctaliatheme";
      displayName = "Noctalia Theme";
      description = "Material You theme generated by noctalia from the current wallpaper";
      version = "0.0.5";
      publisher = "noctalia";
      engines.vscode = "*";
      categories = [ "Themes" ];
      contributes.themes = [
        {
          label = "NoctaliaTheme";
          uiTheme = "vs-dark";
          path = "./themes/NoctaliaTheme-color-theme.json";
        }
      ];
    };
  };
}
