# Rime schema configuration
# encoding: utf-8
#
# vim: ts=2:sts=2:sw=2:fenc=utf-8:et:
#
# 郑码输入法方案定义
# 适用于 中州韻輸入法引擎（https://rime.im/）
#
# ZhengMa is invented by 郑易里教授 & 郑珑女士, Thanks them for this excellent
# Input Method!
#
# Rime 说明书
# https://github.com/rime/home/wiki/UserGuide
# https://github.com/rime/home/wiki/RimeWithSchemata
# https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md
#

schema:
  schema_id: zhengma
  name: "超集郑码"
  version: 2024.05.13
  author:
    - 发明人：郑易里教授 & 郑珑女士
    - 方案制作：梨园茗
  description: |
    超大字符集郑码

    使用 ` 键进行拼音反查词条、编码（依赖于 terra_pinyin，见 recognizer）
    使用 Ctrl+J 或 Ctrl+` 快捷键切换输入方案
    支持简入繁出（基于 OpenCC 简繁转换词典）
  # dependencies:

# 配置切换开关
switches:
  # - name: ascii_mode        # 中英文切换：0-中文，1-英文
    # reset: 1                # 默认为英文
    # states: [ 中文, 英文 ]  # 不使用 switcher/hotkeys 定义的快捷键切换（使用 Shift 切换）
  - name: zh_hant           # 简体→繁體中文切换：0-简体，1-繁體（见 simplifier）
    reset: 0                # 默认为简体中文
    states: [ 简体, 繁體 ]
  - name: extended_charset  # 字符集切换：0-CJK基本字符集，1-CJK扩展字符集
    reset: 0                # 默认显示CJK扩展字符集
    states: [ 常用, 扩展 ]
  - name: full_shape        # 全角→半角字符切换：0-半角，1-全角
    reset: 0                # 默认为半角
    states: [ 半角, 全角 ]
  - name: ascii_punct
    reset: 1
    states: [ 。，, ．， ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
   #- echo_translator       # 没有其他候选字时，回显输入码
    - punct_translator
    - table_translator
    - reverse_lookup_translator
    - lua_translator@time_translate
  filters:
    - simplifier
    - uniquifier
    - reverse_lookup_filter@reverse_lookup_zhengma

# 拼写处理器，接受字符按键，编辑输入
speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  initials: zyxwvutsrqponmlkjihgfedcba
 #delimiter: " '"
  max_code_length: 4                    # 形码最大码长，超过则顶字上屏
  auto_select: true                     # 自动上屏〔true或false〕
  auto_select_pattern: '^;.$|^\w{4}$'   # 自动上屏匹配
  use_space: false                      # 以空格为输入码〔true或false〕
  auto_clear: max_length                # 自动清屏：manual|auto|max_length

translator:
  dictionary: zhengma                   # 翻译器将调取的字典文件
  enable_charset_filter: true           # 是否开启字符集过滤
  enable_sentence: false                # 是否开启自动造句
  sentence_over_completion: false       # 在无全码对应字而仅有逐键提示时也开启智能组句
  enable_encoder: false                 # 是否开启自动造词（同时调整词频）
  encode_commit_history: true           # 是否对已上屏词自动成词
  max_phrase_length: 5                  # 最大自动成词词长
  enable_user_dict: false               # 是否开启用戶词典（同时调整词频）
  initial_quality: 0.75                 # 设定此翻译器出字优先级
  # preedit_format:                       # 上屏码自定义（xlit-变换〔适合大量一对一变换〕）
  #   - xlit|abcdefghijklmnopqrstuvwxyz|ABCDEFGHIJKLMNOPQRSTUVWXYZ|
  # comment_format:                       # 提示码自定义
  #   - xlit|abcdefghijklmnopqrstuvwxyz|ABCDEFGHIJKLMNOPQRSTUVWXYZ|

# 拼音反查词条
reverse_lookup:
  dictionary: rime_ice
  prism: double_pinyin_c
  enable_completion: false              # 提前显示尚未输入完整码的字
  prefix: "`"
  tips: 〔拼音〕
  # preedit_format:                       # 上屏码自定义（xform-改写〔不保留原形〕）
  #   - xform/([nl])v/$1ü/
  #   - xform/([nl])ue/$1üe/
  #   - xform/([jqxy])v/$1u/
  comment_format:                       # 提示码自定义
    - xlit|abcdefghijklmnopqrstuvwxyz|ABCDEFGHIJKLMNOPQRSTUVWXYZ|
    - xform/^/「/
    - xform/$/」/

# 词条反显编码 2018-05-17 17:38:20
reverse_lookup_zhengma:
  tags: [ abc ]                         # abc_segmentor
  dictionary: zhengma
  overwrite_comment: false
  comment_format:
    - xlit|abcdefghijklmnopqrstuvwxyz|ABCDEFGHIJKLMNOPQRSTUVWXYZ|
    - xform/^/「/
    - xform/$/」/

# 快捷键
key_binder:
 #import_preset: default
  bindings:
    - { when: has_menu, accept: semicolon,  send: 2 }        # ; 分号 第二候选
    - { when: has_menu, accept: apostrophe, send: 3 }        # ' 撇号 第三候选
    - { when: has_menu, accept: comma,  send: Page_Up }      # , 逗号 前翻页
    - { when: has_menu, accept: period, send: Page_Down }    # . 句号 后翻页
    - { when: has_menu, accept: minus,  send: Page_Up }      # - 减号 前翻页
    - { when: has_menu, accept: equal,  send: Page_Down }    # = 等号 后翻页

punctuator:
  import_preset: symbols                # 引入 symbols.yaml
  half_shape:
    '/' : [ /, ÷, ／ ]
    '\' : 、
    '=' : =

recognizer:
  import_preset: default                # 引入 default.yaml 中的 recognizer
  patterns:
    reverse_lookup: "`[a-z]*$"          # 拼音反查
    punct: "^/([0-9]0?|[A-Za-z]+)$"     # 配合 symbols.yaml，输入特殊字符

# 配置简体→繁体转换
simplifier:
  option_name: zh_hant
  opencc_config: s2t.json
  tips: char    # 是否提示转换前的字：none/char(仅单字)/all
  excluded_types: [ reverse_lookup ]

