windowrule=isnamedscratchpad:1,width:1200,height:700,appid:musicfox

# Clipse
windowrule=width:1100,height:600,appid:clipse
windowrule=isfloating:1,appid:clipse
windowrule=isoverlay:1,appid:clipse

# Waylyrics
windowrule=isfloating:1,appid:io.github.waylyrics.Waylyrics
windowrule=width:1920,height:100,appid:io.github.waylyrics.Waylyrics
windowrule=isnoborder:1,appid:io.github.waylyrics.Waylyrics
windowrule=offsetx:-100,offsety:-55,appid:io.github.waylyrics.Waylyrics
windowrule=isoverlay:1,appid:io.github.waylyrics.Waylyrics
windowrule=isunglobal:1,appid:io.github.waylyrics.Waylyrics

# WeChat / Vesktop — 录屏时屏蔽内容
windowrule=shield_when_capture:1,appid:wechat
windowrule=shield_when_capture:1,appid:vesktop

# Thunar 重命名对话框
windowrule=isfloating:1,appid:thunar,title:重命名 .*

# Zed — 打开时最大化
windowrule=force_fakemaximize:1,appid:dev.zed.Zed
