# Auto start
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots
exec-once = dbus-update-activation-environment --systemd --all
exec-once = noctalia-shell
exec-once = udiskie
exec-once = waypaper --restore
# exec-once = kitty --class musicfox sh -c musicfox
exec-once = clipse -listen
exec-once = fcitx5 -d
# exec-once = mihomo-party
exec-once = flameshot
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = systemctl --user start hyprpolkitagent.service
# exec-once = clash-verge
