# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# menu and terminal
# bind=Alt,space,spawn,tofi-drun --font /usr/share/fonts/ttf-maple-beta/MapleMono-NF-CN-Regular.ttf --hint-font false --ascii-input true
bind=SUPER,a,spawn,noctalia-shell ipc call launcher toggle
bind=SUPER,Return,spawn,kitty

bind=SUPER,b,spawn,zen
bind=SUPER,e,spawn,dolphin

bind=SUPER,v,spawn_shell,pkill -x clipse || kitty --class clipse -e clipse

bind=SUPER,x,spawn,noctalia-shell ipc call sessionMenu toggle

bind=SUPER+SHIFT,b,spawn,noctalia-shell ipc call bar toggle

bind=SUPER+SHIFT,c,centerwin

# bind=ALT+CRTL,m,toggle_named_scratchpad,musicfox,none,kitty --class musicfox -e musicfox

# exit
bind=SUPER,Delete,quit
bind=SUPER,q,killclient,

# switch window focus
bind=ALT,Tab,focusstack,next
bind=SUPER,j,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,i,focusdir,up
bind=SUPER,k,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=SUPER,Tab,toggleoverview,
bind=SUPER,space,togglefloating,
bind=SUPER,f,togglemaximizescreen,
bind=SUPER+SHIFT,f,togglefullscreen,
bind=SUPER+CTRL,f,togglefakefullscreen,
bind=SUPER,m,minimized,
# bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,m,restore_minimized
bind=ALT,z,toggle_scratchpad

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# switch layout
bind=SUPER,n,switch_layout

# tag switch
bind=SUPER,u,viewtoleft,0
# bind=CTRL,Left,viewtoleft_have_client,0
bind=SUPER,o,viewtoright,0
# bind=CTRL,Right,viewtoright_have_client,0
bind=SUPER+SHIFT,u,tagtoleft,0
bind=SUPER+SHIFT,o,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+CTRL,1,tagsilent,1,0
bind=SUPER+CTRL,2,tagsilent,2,0
bind=SUPER+CTRL,3,tagsilent,3,0
bind=SUPER+CTRL,4,tagsilent,4,0
bind=SUPER+CTRL,5,tagsilent,5,0
bind=SUPER+CTRL,6,tagsilent,6,0
bind=SUPER+CTRL,7,tagsilent,7,0
bind=SUPER+CTRL,8,tagsilent,8,0
bind=SUPER+CTRL,9,tagsilent,9,0

# monitor switch
# bind=alt+shift,Left,focusmon,left
# bind=alt+shift,Right,focusmon,right
# bind=SUPER+Alt,Left,tagmon,left
# bind=SUPER+Alt,Right,tagmon,right

# gaps
# bind=ALT+SHIFT,X,incgaps,1
# bind=ALT+SHIFT,Z,incgaps,-1
# bind=ALT+SHIFT,R,togglegaps

# movewin
bind=SUPER+SHIFT,i,movewin,+0,-50
bind=SUPER+SHIFT,k,movewin,+0,+50
bind=SUPER+SHIFT,j,movewin,-50,+0
bind=SUPER+SHIFT,l,movewin,+50,+0

# resizewin
bind=SUPER+ALT,i,resizewin,+0,-50
bind=SUPER+ALT,k,resizewin,+0,+50
bind=SUPER+ALT,j,resizewin,-50,+0
bind=SUPER+ALT,l,resizewin,+50,+0

# Mouse Button Bindings
# NONE mode key only work in ov mode
mousebind=SUPER,btn_left,moveresize,curmove
# mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_left,toggleoverview,1
mousebind=NONE,btn_right,killclient,0

# Axis Bindings
axisbind=SUPER,UP,viewtoleft
axisbind=SUPER,DOWN,viewtoright
