windowrule=isnamedscratchpad:1,width:1200,height:700,appid:musicfox

# Clipse
windowrule=width:1100,height:500,appid:clipse
windowrule=isfloating:1,appid:clipse
windowrule=isoverlay:1,appid:clipse

# Waylyrics
windowrule=isfloating:1,appid:io.github.waylyrics.Waylyrics
windowrule=width:1920,height:100,appid:io.github.waylyrics.Waylyrics
windowrule=isnoborder:1,appid:io.github.waylyrics.Waylyrics
windowrule=offsetx:-100,offsety:-55,appid:io.github.waylyrics.Waylyrics
windowrule=isoverlay:1,appid:io.github.waylyrics.Waylyrics
windowrule=isunglobal:1,appid:io.github.waylyrics.Waylyrics
