# patch:
#   speller/algebra:
#     - derive/a/AA/
#     - derive/a/AY/
#     - derive/ai/AI/
#     - derive/an/AN/
#     - derive/ang/AG/
#     - derive/ao/AO/
#     - derive/bang/BM/
#     - derive/bei/B;/
#     - derive/bian/BL/
#     - derive/biao/BB/
#     - derive/bin/BN/
#     - derive/bing/BP/
#     - derive/ce/CY/
#     - derive/ceng/CN/
#     - derive/chai/IX/
#     - derive/chan/IW/
#     - derive/chao/IJ/
#     - derive/chen/IT/
#     - derive/chi/IF/
#     - derive/chi/IH/
#     - derive/chong/IL/
#     - derive/chou/IQ/
#     - derive/chu/IV/
#     - derive/chuan/IR/
#     - derive/chui/IS/
#     - derive/chui/I;/
#     - derive/chuo/IB/
#     - derive/cui/C;/
#     - derive/cui/CV/
#     - derive/cun/C;/
#     - derive/de/D;/
#     - derive/deng/DN/
#     - derive/dia/DX/
#     - derive/diao/DB/
#     - derive/duan/DM/
#     - derive/duan/DR/
#     - derive/dui/DS/
#     - derive/dui/DV/
#     - derive/dun/D;/
#     - derive/e/EY/
#     - derive/ei/EI/
#     - derive/eing/EP/
#     - derive/en/EN/
#     - derive/eng/EG/
#     - derive/er/E;/
#     - derive/fa/FJ/
#     - derive/fa/FF/
#     - derive/fang/FH/
#     - derive/fei/FI/
#     - derive/fei/F;/
#     - derive/ge/GY/
#     - derive/gei/GI/
#     - derive/geng/GN/
#     - derive/gua/GA/
#     - derive/guai/GH/
#     - derive/guan/GM/
#     - derive/guang/GF/
#     - derive/gui/GS/
#     - derive/gun/G;/
#     - derive/han/HW/
#     - derive/hao/HF/
#     - derive/hen/HD/
#     - derive/hou/HQ/
#     - derive/hu/HV/
#     - derive/hua/HA/
#     - derive/hua/HT/
#     - derive/huan/HR/
#     - derive/hui/HV/
#     - derive/huo/HB/
#     - derive/ji/JD/
#     - derive/jia/JA/
#     - derive/jie/JE/
#     - derive/jiong/JL/
#     - derive/juan/JR/
#     - derive/jue/JB/
#     - derive/kan/KW/
#     - derive/kao/KF/
#     - derive/ken/KD/
#     - derive/kong/KL/
#     - derive/kou/KQ/
#     - derive/ku/KV/
#     - derive/kua/KA/
#     - derive/kua/KT/
#     - derive/kuan/KR/
#     - derive/kui/KS/
#     - derive/kui/K;/
#     - derive/kuo/KB/
#     - derive/lai/LX/
#     - derive/lai/LH/
#     - derive/lei/LS/
#     - derive/leng/LN/
#     - derive/li/LD/
#     - derive/lie/LY/
#     - derive/lou/LQ/
#     - derive/lu/LV/
#     - derive/luan/LR/
#     - derive/lue/LB/
#     - derive/luo/LB/
#     - derive/mai/MX/
#     - derive/man/MK/
#     - derive/mao/MJ/
#     - derive/mei/MS/
#     - derive/men/MD/
#     - derive/mi/MZ/
#     - derive/miao/MB/
#     - derive/mie/ME/
#     - derive/mo/ME/
#     - derive/mo/MB/
#     - derive/mou/MQ/
#     - derive/mu/MV/
#     - derive/nai/NX/
#     - derive/nan/NK/
#     - derive/nao/NJ/
#     - derive/nei/NS/
#     - derive/nen/ND/
#     - derive/ni/NZ/
#     - derive/niao/NB/
#     - derive/nie/NE/
#     - derive/nu/NV/
#     - derive/nuan/NR/
#     - derive/nue/NB/
#     - derive/nuo/NB/
#     - derive/o/OY/
#     - derive/ou/OU/
#     - derive/pai/PX/
#     - derive/pai/PH/
#     - derive/pan/PK/
#     - derive/pei/PS/
#     - derive/pi/PE/
#     - derive/pia/PX/
#     - derive/pie/PY/
#     - derive/po/PB/
#     - derive/pou/PQ/
#     - derive/qia/QL/
#     - derive/qian/QK/
#     - derive/qiang/QH/
#     - derive/qin/QN/
#     - derive/qing/QP/
#     - derive/qiong/QF/
#     - derive/qiu/QO/
#     - derive/qjiao/QJ/
#     - derive/quan/QM/
#     - derive/quan/QR/
#     - derive/qun/Q;/
#     - derive/qun/QT/
#     - derive/rang/RH/
#     - derive/re/RY/
#     - derive/reng/RN/
#     - derive/rui/R;/
#     - derive/rui/RV/
#     - derive/run/R;/
#     - derive/run/RT/
#     - derive/se/SY/
#     - derive/shai/OX/
#     - derive/shan/OW/
#     - derive/shao/AJ/
#     - derive/shao/OJ/
#     - derive/shen/AK/
#     - derive/shen/OT/
#     - derive/shi/AH/
#     - derive/shi/OF/
#     - derive/shou/OQ/
#     - derive/shu/AU/
#     - derive/shu/OV/
#     - derive/shua/OT/
#     - derive/shuan/OR/
#     - derive/shui/OS/
#     - derive/shui/O;/
#     - derive/shuo/OB/
#     - derive/suan/SM/
#     - derive/suan/SR/
#     - derive/sui/S;/
#     - derive/sui/SV/
#     - derive/sun/S;/
#     - derive/sun/ST/
#     - derive/tang/TM/
#     - derive/te/TY/
#     - derive/tian/TN/
#     - derive/ting/TS/
#     - derive/tjiao/TJ/
#     - derive/tuan/TM/
#     - derive/tuan/TR/
#     - derive/tui/T;/
#     - derive/tun/T;/
#     - derive/tun/TT/
#     - derive/wa/WJ/
#     - derive/wa/WW/
#     - derive/wei/WI/
#     - derive/wei/W;/
#     - derive/xia/XL/
#     - derive/xian/XK/
#     - derive/xiang/XH/
#     - derive/xin/XN/
#     - derive/xing/XP/
#     - derive/xiong/XF/
#     - derive/xiu/XO/
#     - derive/xjiao/XJ/
#     - derive/xuan/XM/
#     - derive/xun/X;/
#     - derive/yan/YW/
#     - derive/yan/EK/
#     - derive/yang/EG/
#     - derive/yang/EH/
#     - derive/yao/EJ/
#     - derive/yi/EI/
#     - derive/yin/EN/
#     - derive/ying/EP/
#     - derive/yong/EL/
#     - derive/you/EO/
#     - derive/you/YQ/
#     - derive/yu/EU/
#     - derive/yuan/EM/
#     - derive/yue/YB/
#     - derive/yue/E;/
#     - derive/za/ZM/
#     - derive/za/ZZ/
#     - derive/ze/ZY/
#     - derive/zeng/ZN/
#     - derive/zhai/UX/
#     - derive/zhai/VH/
#     - derive/zhan/UW/
#     - derive/zhao/VJ/
#     - derive/zhen/UT/
#     - derive/zhen/VK/
#     - derive/zhi/UF/
#     - derive/zhi/VI/
#     - derive/zhong/UL/
#     - derive/zhong/VL/
#     - derive/zhou/UQ/
#     - derive/zhu/UV|VU/
#     - derive/zhua/UT/
#     - derive/zhuan/UR/
#     - derive/zhui/US/
#     - derive/zhui/U;/
#     - derive/zhuo/UB/
#     - derive/zuan/ZM/
#     - derive/zui/Z;/
#     - derive/zui/ZV/
#     - derive/zun/Z;/
#     - derive/lie/LZ/
#     - derive/pie/PZ/
#     - derive/jie/JZ/
#     - derive/^(\w)ai$/$1H/
#     - derive/^(\w)an$/$1K/
#     - derive/^(\w)ang$/$1G/
#     - derive/^(\w)ao$/$1J/
#     - derive/^(\w)ei$/$1;/
#     - derive/^(\w)en$/$1N/
#     - derive/^(\w)eng$/$1D/
#     - derive/^(\w)ia$/$1L/
#     - derive/^(\w)ian$/$1W/
#     - derive/^(\w)iang$/$1G/
#     - derive/^(\w)iao$/$1J/
#     - derive/^(\w)ie$/$1Y/
#     - derive/^(\w)in$/$1T/
#     - derive/^(\w)ing$/$1F/
#     - derive/^(\w)iong$/$1L/
#     - derive/^(\w)iu$/$1Q/
#     - derive/^(\w)ong$/$1L/
#     - derive/^(\w)ou$/$1O/
#     - derive/^(\w)ua$/$1A/
#     - derive/^(\w)uai$/$1X/
#     - derive/^(\w)uan$/$1M/
#     - derive/^(\w)uang$/$1Z/
#     - derive/^(\w)ue$/$1;/
#     - derive/^(\w)ui$/$1S/
#     - derive/^(\w)un$/$1C/
#     - derive/^(\w)uo$/$1P/
#     - derive/^y/E/
#     - derive/^sh/O/
#     - derive/^zh/U/
#     - derive/^ch/I/

#     - xlit/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/

# patch:
#   speller/algebra:
#     - derive/([nl])ü/$1v/
#     - derive/([nl])üe/$1ue/
#     - derive/([nl])üe/$1ve/
#     - derive/([jqxy])u/$1v/
#     - derive/ve$/ue/
#     # 拼写运算：C双拼方案
#     - derive/fa/FJ/
#     - derive/bang/BM/
#     - derive/bei/B;/
#     - derive/ji/JD/
#     - derive/bin/BK/
#     - derive/cou/CO/
#     - derive/cuan/CM/
#     - derive/gun/G;/
#     - derive/wa/WJ/
#     - derive/cang/CG/
#     - derive/fei/FI/
#     - derive/li/LD/
#     - derive/jin/JT/
#     - derive/chou/UQ/
#     - derive/chuan/UR/
#     - derive/qun/Q;/
#     - derive/za/ZM/
#     - derive/tang/TM/
#     - derive/gei/GS/
#     - derive/mi/MZ/
#     - derive/lin/LT/
#     - derive/dou/DO/
#     - derive/duan/DM/
#     - derive/run/R;/
#     - derive/wang/WG/
#     - derive/hei/HS/
#     - derive/ni/NZ/
#     - derive/min/MT/
#     - derive/fou/FO/
#     - derive/guan/GM/
#     - derive/sun/S;/
#     - derive/a/AH/
#     - derive/chang/UG/
#     - derive/lei/LS/
#     - derive/pi/PE/
#     - derive/nin/NT/
#     - derive/gou/GO/
#     - derive/huan/HR/
#     - derive/tun/T;/
#     - derive/dang/DG/
#     - derive/mei/MS/
#     - derive/pin/PT/
#     - derive/hou/HQ/
#     - derive/juan/JR/
#     - derive/cun/CC/
#     - derive/fang/FH/
#     - derive/nei/NS/
#     - derive/qin/QK/
#     - derive/kou/KQ/
#     - derive/kuan/KR/
#     - derive/chun/UC/
#     - derive/cha/UA/
#     - derive/gang/GG/
#     - derive/pei/PS/
#     - derive/xin/XK/
#     - derive/lou/LQ/
#     - derive/luan/LR/
#     - derive/dun/DC/
#     - derive/hang/HG/
#     - derive/wei/WI/
#     - derive/shi/IS/
#     - derive/yin/EK/
#     - derive/mou/MQ/
#     - derive/nuan/NR/
#     - derive/hun/HC/
#     - derive/kang/KG/
#     - derive/zei/Z;/
#     - derive/bing/BP/
#     - derive/nou/NQ/
#     - derive/quan/QM/
#     - derive/jun/JC/
#     - derive/lang/LG/
#     - derive/ben/BK/
#     - derive/ding/DF/
#     - derive/pou/PQ/
#     - derive/ruan/RM/
#     - derive/kun/KC/
#     - derive/mang/MG/
#     - derive/cen/CK/
#     - derive/yi/EI/
#     - derive/jing/JF/
#     - derive/rou/RO/
#     - derive/suan/SM/
#     - derive/lun/LC/
#     - derive/nang/NG/
#     - derive/chen/UT/
#     - derive/ling/LF/
#     - derive/sou/SO/
#     - derive/shuan/IR/
#     - derive/shun/IC/
#     - derive/pang/PG/
#     - derive/fen/FK/
#     - derive/zhi/VI/
#     - derive/ming/MF/
#     - derive/shou/IQ/
#     - derive/tuan/TM/
#     - derive/xun/XC/
#     - derive/rang/RH/
#     - derive/gen/GK/
#     - derive/dia/DX/
#     - derive/ning/NF/
#     - derive/tou/TO/
#     - derive/xuan/XM/
#     - derive/yun/YC/
#     - derive/sang/SG/
#     - derive/hen/HD/
#     - derive/xia/XL/
#     - derive/ping/PF/
#     - derive/you/EO/
#     - derive/yuan/EM/
#     - derive/zun/ZC/
#     - derive/sha/IA/
#     - derive/shang/IG/
#     - derive/ken/KD/
#     - derive/lia/LX/
#     - derive/qing/QP/
#     - derive/zou/ZO/
#     - derive/zuan/ZM/
#     - derive/zhun/OC/
#     - derive/yang/EG/
#     - derive/men/MD/
#     - derive/jia/JA/
#     - derive/ting/TP/
#     - derive/zhou/OQ/
#     - derive/zhuan/OR/
#     - derive/cuo/CP/
#     - derive/zang/ZG/
#     - derive/nen/NK/
#     - derive/qia/QL/
#     - derive/xing/XP/
#     - derive/er/EH/
#     - derive/chuang/UZ/
#     - derive/chuo/UP/
#     - derive/zha/OA/
#     - derive/zhang/OG/
#     - derive/pen/PK/
#     - derive/bian/BL/
#     - derive/ying/EP/
#     - derive/guang/GZ/
#     - derive/duo/DP/
#     - derive/bai/BH/
#     - derive/bao/BJ/
#     - derive/ren/RK/
#     - derive/tian/TK/
#     - derive/jiong/JS/
#     - derive/huang/HZ/
#     - derive/guo/GP/
#     - derive/cai/CH/
#     - derive/cao/CJ/
#     - derive/sen/SK/
#     - derive/dian/DW/
#     - derive/qiong/QL/
#     - derive/chu/UF/
#     - derive/kuang/KZ/
#     - derive/huo/HB/
#     - derive/chai/UX/
#     - derive/chao/UB/
#     - derive/shen/IT/
#     - derive/jian/JW/
#     - derive/xiong/XL/
#     - derive/shuang/IZ/
#     - derive/kuo/KB/
#     - derive/dai/DH/
#     - derive/dao/DJ/
#     - derive/wen/WK/
#     - derive/lian/LW/
#     - derive/diu/DQ/
#     - derive/zhuang/OZ/
#     - derive/luo/LB/
#     - derive/gai/GH/
#     - derive/gao/GJ/
#     - derive/zen/ZK/
#     - derive/mian/MW/
#     - derive/jiu/JQ/
#     - derive/jue/JB/
#     - derive/nuo/NP/
#     - derive/hai/HH/
#     - derive/hao/HJ/
#     - derive/zhen/OT/
#     - derive/nian/NW/
#     - derive/liu/LQ/
#     - derive/hu/HF/
#     - derive/lue/LB/
#     - derive/ruo/RP/
#     - derive/kai/KH/
#     - derive/kao/KJ/
#     - derive/beng/BD/
#     - derive/pian/PW/
#     - derive/miu/MQ/
#     - derive/ju/JV/
#     - derive/nue/N;/
#     - derive/suo/SP/
#     - derive/lai/LH/
#     - derive/lao/LJ/
#     - derive/ceng/CK/
#     - derive/qian/QN/
#     - derive/niu/NQ/
#     - derive/ku/KF/
#     - derive/que/Q;/
#     - derive/shuo/IB/
#     - derive/mai/MX/
#     - derive/mao/MB/
#     - derive/cheng/UD/
#     - derive/xian/XN/
#     - derive/qiu/QO/
#     - derive/lu/LV/
#     - derive/xue/X;/
#     - derive/tuo/TP/
#     - derive/nai/NX/
#     - derive/nao/NB/
#     - derive/deng/DD/
#     - derive/jiang/JG/
#     - derive/xiu/XO/
#     - derive/mu/MV/
#     - derive/yue/E;/
#     - derive/zuo/ZP/
#     - derive/pai/PH/
#     - derive/pao/PJ/
#     - derive/feng/FD/
#     - derive/liang/LG/
#     - derive/nu/NV/
#     - derive/cui/C;/
#     - derive/zhuo/OB/
#     - derive/sai/SH/
#     - derive/rao/RJ/
#     - derive/geng/GK/
#     - derive/niang/NG/
#     - derive/sui/S;/
#     - derive/shai/IX/
#     - derive/sao/SJ/
#     - derive/heng/HD/
#     - derive/qiang/QH/
#     - derive/ang/AG/
#     - derive/pu/PV/
#     - derive/zui/Z;/
#     - derive/tai/TH/
#     - derive/shao/AJ/
#     - derive/keng/KD/
#     - derive/xiang/XH/
#     - derive/mo/MQ/
#     - derive/chui/UV/
#     - derive/wai/WH/
#     - derive/tao/TJ/
#     - derive/leng/LK/
#     - derive/biao/BB/
#     - derive/po/PQ/
#     - derive/dui/D;/
#     - derive/zai/ZH/
#     - derive/yao/EJ/
#     - derive/meng/MD/
#     - derive/diao/DB/
#     - derive/gui/G;/
#     - derive/zhai/OX/
#     - derive/zao/ZJ/
#     - derive/neng/ND/
#     - derive/jiao/JJ/
#     - derive/shu/IF/
#     - derive/hui/HV/
#     - derive/ban/BN/
#     - derive/zhao/OJ/
#     - derive/peng/PD/
#     - derive/liao/LZ/
#     - derive/o/OH/
#     - derive/kui/KV/
#     - derive/can/CN/
#     - derive/ge/GI/
#     - derive/reng/RD/
#     - derive/miao/MB/
#     - derive/rui/R;/
#     - derive/chan/UW/
#     - derive/ce/CY/
#     - derive/seng/SK/
#     - derive/niao/NB/
#     - derive/yo/EO/
#     - derive/shui/IV/
#     - derive/dan/DN/
#     - derive/che/UE/
#     - derive/sheng/ID/
#     - derive/piao/PJ/
#     - derive/cong/CL/
#     - derive/yu/EU/
#     - derive/tui/T;/
#     - derive/fan/FN/
#     - derive/de/DK/
#     - derive/teng/TD/
#     - derive/qiao/QJ/
#     - derive/chong/US/
#     - derive/zhui/OV/
#     - derive/gan/GN/
#     - derive/e/E;/
#     - derive/weng/WD/
#     - derive/tiao/TJ/
#     - derive/dong/DL/
#     - derive/zhu/OF/
#     - derive/han/HW/
#     - derive/zeng/ZK/
#     - derive/xiao/XJ/
#     - derive/gong/GL/
#     - derive/gua/GA/
#     - derive/kan/KW/
#     - derive/zheng/OD/
#     - derive/bie/BY/
#     - derive/hong/HL/
#     - derive/hua/HA/
#     - derive/lan/LN/
#     - derive/die/DY/
#     - derive/kong/KS/
#     - derive/kua/KM/
#     - derive/man/MN/
#     - derive/jie/JE/
#     - derive/long/LL/
#     - derive/shua/IM/
#     - derive/nan/NN/
#     - derive/lie/LZ/
#     - derive/nong/NL/
#     - derive/zhua/OM/
#     - derive/pan/PN/
#     - derive/re/RY/
#     - derive/chi/;I/
#     - derive/mie/ME/
#     - derive/rong/RL/
#     - derive/chuai/UX/
#     - derive/ran/RN/
#     - derive/se/SY/
#     - derive/nie/NE/
#     - derive/song/SL/
#     - derive/guai/GH/
#     - derive/san/SN/
#     - derive/she/IE/
#     - derive/pie/PZ/
#     - derive/tong/TL/
#     - derive/huai/HX/
#     - derive/shan/IW/
#     - derive/te/TY/
#     - derive/qie/QY/
#     - derive/yong/EL/
#     - derive/kuai/KX/
#     - derive/tan/TN/
#     - derive/tie/TY/
#     - derive/zong/ZL/
#     - derive/shuai/IX/
#     - derive/wan/WN/
#     - derive/ze/ZY/
#     - derive/xie/XY/
#     - derive/zhong/OS/
#     - derive/zhuai/OX/
#     - derive/yan/EN/
#     - derive/zhe/OE/
#     - derive/zan/ZN/
#     - derive/zhan/OW/

#     - derive/^y/E/
#     - derive/^sh/A/
#     - derive/^zh/V/
#     - xform/^ch/U/
#     - xform/^sh/I/
#     - xform/^zh/O/

#     - derive/^(\w)ou$/$1Q/
#     - derive/^(\w)an$/$1W/
#     - derive/^(\w)ie$/$1E/
#     - derive/^(\w)ua$/$1T/
#     - derive/^(\w)en$/$1T/
#     - derive/^(\w)iu$/$1O/
#     - derive/^(\w)ing$/$1P/
#     - derive/^(\w)ong$/$1S/
#     - derive/^(\w)en$/$1D/
#     - derive/^(\w)u$/$1F/
#     - derive/^(\w)uai$/$1H/
#     - derive/^(\w)ang$/$1H/
#     - derive/^(\w)iang$/$1H/
#     - derive/^(\w)in$/$1K/
#     - derive/^(\w)ian$/$1K/
#     - derive/^(\w)ia$/$1L/
#     - derive/^(\w)iong$/$1L/
#     - derive/^(\w)ei$/$1;/
#     - derive/^(\w)un$/$1;/
#     - derive/^(\w)ue$/$1;/
#     - derive/^(\w)ie$/$1E/
#     - derive/^(\w)ie$/$1;/
#     - derive/^(\w)ie$/$1Z/
#     - derive/^(\w)ai$/$1X/
#     - derive/^(\w)ia$/$1X/
#     - derive/^(\w)iao$/$1B/
#     - derive/^(\w)ue$/$1B/
#     - derive/^(\w)uo$/$1B/
#     - derive/^(\w)ao$/$1B/
#     - derive/^(\w)ian$/$1N/
#     - derive/^(\w)ua$/$1M/
#     - derive/^(\w)uan$/$1R/
#     - derive/^(\w)ui$/$1;/

#     - xform/^(\w)uang$/$1Z/
#     - xform/^(\w)iang$/$1G/
#     - xform/^(\w)ian$/$1W/
#     - xform/^(\w)iao$/$1J/
#     - xform/^(\w)uai$/$1X/
#     - xform/^(\w)uan$/$1M/
#     - xform/^(\w)ua$/$1A/
#     - xform/^(\w)ia$/$1A/
#     - xform/^(\w)iong$/$1L/
#     - xform/^(\w)uo$/$1P/

#     - xform/^(\w)eng$/$1D/
#     - xform/^(\w)ing$/$1F/
#     - xform/^(\w)ang$/$1G/
#     - xform/^(\w)iu$/$1Q/
#     - xform/^(\w)ie$/$1Y/
#     - xform/^(\w)in$/$1T/
#     - xform/^(\w)ou$/$1O/
#     - xform/^(\w)ei$/$1S/
#     - xform/^(\w)ai$/$1H/
#     - xform/^(\w)ao$/$1J/
#     - xform/^(\w)en$/$1K/
#     - xform/^(\w)ong$/$1L/
#     - xform/^(\w)ue$/$1;/
#     - xform/^(\w)üe$/$1;/
#     - xform/^(\w)ve$/$1;/
#     - xform/^(\w)un$/$1C/
#     - xform/^(\w)ui$/$1V/
#     - xform/^(\w)an$/$1N/

#     - xlit/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/