customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.1
  generator: "Rime::SwitcherSettings"
  modified_time: "Thu Jun 20 23:23:53 2024"
  rime_version: 1.11.2
patch:
  schema_list:
    - {schema: wubi98}
    - {schema: double_pinyin_c}
    - {schema: japanese}
    # - {schema: luna_pinyin_simp}