distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.16.1
install_time: "Sat Apr 20 13:52:46 2024"
installation_id: MatebookE
rime_version: 1.11.2
update_time: "Thu Jun  6 21:40:02 2024"