---
name: people
version: "2024-06-22"
sort: by_weight
use_preset_vocabulary: true
...

孙晨芯	sun chen xin
宋雨霏	song yu fei
李文博	li wen bo
杨嘉熙	yang jia xi
王珈瑞	wang jia rui
花国源	hua guo yuan
蔡明轩	cai ming xuan
詹智涵	zhan zhi han
金宏霖	jin hong lint
韩明轩	han ming xuan