var:
  last_build_time: 1719123495
  option:
    ascii_punct: false
    full_shape: true
    traditionalization: false
  previously_selected_schema: double_pinyin_c
  schema_access_time:
    double_pinyin_c: 1719110201
    flypy_flypy: 1718360875
    japanese: 1719110194
    luna_pinyin_simp: 1718279276
    reverse_moqima: 1717849032
    wubi98: 1718897084
    wubi98_ci: 1718896871
    wubi98_mint: 1717320492
    wubi98single: 1717326300