[pyprland]
plugins = [
    "toggle_special",
    "fetch_client_menu",
    "expose",
    # "external:fcitx5_switcher",
    # "external:hdrop",
    "cloud_pyprland.fcitx5_switcher",
    "cloud_pyprland.hdrop",
    # "cloud_pyprland.sleepy",
    # "sleepy",
    # "external:sleepy",
]
# plugins_paths = ["/home/rhencloud/Project/cloud-pyprland/cloud-pyprland"]

# cloud_pyprland plugin configuration (use nested tables, no quotes)
["cloud_pyprland.sleepy"]
server_url = "https://sleepy.rhen.cloud"
device_name = "Arch Linux"
device_id = "archlinux"
token = "ljr811226"


["cloud_pyprland.fcitx5_switcher"]
active_classes = ["wechat", "QQ", "zoom"]
inactive_classes = [
    "code",
    "kitty",
    "musicfox",
    "google-chrome",
    "clipse",
    "org.wezfurlong.wezterm",
    "firefox",
]
active_titles = ["微信"]
inactive_titles = ["Minecraft .*"]

# 在这里定义多个应用，之后可使用 `pypr hdrop <app>` 直接调用
["cloud_pyprland.hdrop".wechat]
class = "wechat"
floating = true
center = true
height = 700
width = 1000
launch_on_missing = false

["cloud_pyprland.hdrop".musicfox]
class = "musicfox"
command = "kitty --class musicfox musicfox"
floating = true
center = true
height = 700
width = 1200
launch_on_missing = true
